/* 
 * File:   Interrupt_internal.h
 * Author: es-IslamSameh2025
 *
 * Created on February 18, 2024, 9:31 PM
 */

#ifndef INTERRUPT_INTERNAL_H
#define	INTERRUPT_INTERNAL_H
#include "Interrupt_declaration.h"
/*ADC START */
#if ADC_INTERRUPT_FEATURE_ENABLE==ACTIVATED
#define ADC_INTERRUPT_ENABLE()             (PIE1bits.ADIE=1)
#define ADC_INTERRUPT_DISABLE()            (PIE1bits.ADIE=0)
#define ADC_INTERRUPT_FLAG_CLEAR()         (PIR1bits.ADIF=0)
#if INTERRUPT_PRIORITY_ACTIVATION==ACTIVATED
#define ADC_INTERRUPT_HIGH_PRIORITY()      (IPR1bits.ADIP=1)
#define ADC_INTERRUPT_LOW_PRIORITY()       (IPR1bits.ADIP=0)
#endif
#endif
/*ADC END*/

/*TIMER0 START */
#if TIMER0_INTERRUPT_FEATURE_ENABLE==ACTIVATED
#define TIMER0_INTERRUPT_ENABLE()             (INTCONbits.TMR0IE=1)
#define TIMER0_INTERRUPT_DISABLE()            (INTCONbits.TMR0IE=0)
#define TIMER0_INTERRUPT_FLAG_CLEAR()         (INTCONbits.TMR0IF=0)
#if INTERRUPT_PRIORITY_ACTIVATION==ACTIVATED
#define TIMER0_INTERRUPT_HIGH_PRIORITY()      (INTCON2bits.TMR0IP=1)
#define TIMER0_INTERRUPT_LOW_PRIORITY()       (INTCON2bits.TMR0IP=0)
#endif
#endif
/*TIMER0 END*/

/*TIMER1 START */
#if TIMER1_INTERRUPT_FEATURE_ENABLE==ACTIVATED
#define TIMER1_INTERRUPT_ENABLE()             (PIE1bits.TMR1IE=1)
#define TIMER1_INTERRUPT_DISABLE()            (PIE1bits.TMR1IE=0)
#define TIMER1_INTERRUPT_FLAG_CLEAR()         (PIR1bits.TMR1IF=0)
#if INTERRUPT_PRIORITY_ACTIVATION==ACTIVATED
#define TIMER1_INTERRUPT_HIGH_PRIORITY()      (IPR1bits.TMR1IP=1)
#define TIMER1_INTERRUPT_LOW_PRIORITY()       (IPR1bits.TMR1IP=0)
#endif
#endif
/*TIMER1 END*/

/*TIMER2 START */
#if TIMER2_INTERRUPT_FEATURE_ENABLE==ACTIVATED
#define TIMER2_INTERRUPT_ENABLE()             (PIE1bits.TMR2IE=1)
#define TIMER2_INTERRUPT_DISABLE()            (PIE1bits.TMR2IE=0)
#define TIMER2_INTERRUPT_FLAG_CLEAR()         (PIR1bits.TMR2IF=0)
#if INTERRUPT_PRIORITY_ACTIVATION==ACTIVATED
#define TIMER2_INTERRUPT_HIGH_PRIORITY()      (IPR1bits.TMR2IP=1)
#define TIMER2_INTERRUPT_LOW_PRIORITY()       (IPR1bits.TMR2IP=0)
#endif
#endif
/*TIMER2 END*/

/*TIMER3 START */
#if TIMER3_INTERRUPT_FEATURE_ENABLE==ACTIVATED
#define TIMER3_INTERRUPT_ENABLE()             (PIE2bits.TMR3IE=1)
#define TIMER3_INTERRUPT_DISABLE()            (PIE2bits.TMR3IE=0)
#define TIMER3_INTERRUPT_FLAG_CLEAR()         (PIR2bits.TMR3IF=0)
#if INTERRUPT_PRIORITY_ACTIVATION==ACTIVATED
#define TIMER3_INTERRUPT_HIGH_PRIORITY()      (IPR2bits.TMR3IP=1)
#define TIMER3_INTERRUPT_LOW_PRIORITY()       (IPR2bits.TMR3IP=0)
#endif
#endif
/*TIMER3 END*/

#endif	/* INTERRUPT_INTERNAL_H */

